### ISSUE TITLE
[TypeError: _data$lastSeen.toMillis is not a function. (In '_data$lastSeen.toMillis()', '_data$lastSeen.toMillis' is undefined)]

### ISSUE THREAD

**Issue by muratneciparcans** [flyerhq/react-native-firebase-chat-core#24]
I tried to create a room but I'm getting **`_data$lastSeen.toMillis is not a function`** 
How can I solve this?

Thank you.

**Comment by zenplaylabs** [comment]
still facing the same error

**Comment by zenplaylabs** [comment]
is it wise to still use FlyerChat react-native in 2023? are there any better actively maintained, feature rich chat plugins available?

**Comment by demchenkoalex** [comment]
This library is not maintained for years now. Please don't use.

**Comment by zenplaylabs** [comment]
Thanks for confirming! Will look out for other react-native chat sdk options.

**Comment by zenplaylabs** [comment]
If no support is provided now, can we please update the description in the Github page Bio (for react-native) ?
This is totally misleading: "Actively maintained, community-driven Firebase BaaS for chat applications with an optional chat UI" and folks will end up spending time on an unsupported repo.

**Comment by demchenkoalex** [comment]
Flutter works actually it is like a year or two ahead of react native. Will update RN.
