### ISSUE TITLE
Unable to install example

### ISSUE THREAD

**Issue by majirosstefan** [flyerhq/react-native-firebase-chat-core#35]
<img width="762" alt="Screen Shot 2023-03-04 at 6 13 44 PM" src="https://user-images.githubusercontent.com/44647381/222919553-04b63f46-22e8-426a-a5a9-b07c317b3639.png">

There are no changes in Info.plist file, I am using M1 machine.

EDIT: solved now - I needed to re-add Google Plist file, as it was not copied properly on the first time. You can close this issue.

**Comment by demchenkoalex** [comment]
Thanks!
