### ISSUE TITLE
"User is typing" does Flyer chat support this ?

### ISSUE THREAD

**Issue by zenplaylabs** [flyerhq/react-native-firebase-chat-core#37]
Does Flyer chat support "typing" or some animation while the other user is typing or some flag to enable it?

**Comment by demchenkoalex** [comment]
Yes, you need to provide `typingIndicatorOptions` see the implementation with comments https://github.com/flyerhq/flutter_chat_ui/blob/main/lib/src/widgets/typing_indicator.dart#L430
