### ISSUE TITLE
Preview of an image before uploading it and sending it

### ISSUE THREAD

**Issue by superaldo** [flyerhq/react-native-firebase-chat-core#39]
Hello 👋 
Could someone give me an idea of how to implement a full screen preview of an image before uploading it and sending it as a message?

similar to when you tap on a bubble with an image you see a full screen preview with a close button(X), I would like to know if something like that can be implemented but just before sending the image after selecting it from the ImagePicker

**Comment by demchenkoalex** [comment]
You probably should not use this library cause I am not working on it for quite some time, but answering your question not in terms of the library, but in general - yes, it is possible. When you pick an image you can open a full screen preview with potentially custom input below for the caption and a send button. This way you can see full image and also add a caption using 1 action. Later this can be improved adding markdown tools etc. Not sure how multi pick should work though 🤔
